# Sentence Embedding

In [ ]:
texts = [
    "Artificial intelligence is transforming the way we work.",
    "AI is changing how people perform their jobs.",
    "Global warming is impacting weather all over the planet.",
    "I enjoy hiking in the mountains during summer."
]

# Using *langchain_huggingface*

In [ ]:
!pip install langchain_huggingface --quiet

In [ ]:
from langchain_huggingface import HuggingFaceEmbeddings
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

In [ ]:
embedding_name = 'sentence-transformers/all-mpnet-base-v2'
embeddings = HuggingFaceEmbeddings(model_name=embedding_name)


vectors = [embeddings.embed_query(text) for text in texts]
vectors_np = np.array(vectors)

cos_sim_matrix = cosine_similarity(vectors_np)


In [ ]:
print(cos_sim_matrix)

[[ 1.          0.8534016   0.16450774 -0.02841136]
 [ 0.8534016   1.          0.17911438 -0.028706  ]
 [ 0.16450774  0.17911438  1.          0.20894329]
 [-0.02841136 -0.028706    0.20894329  1.        ]]


# Using *sentence_transformers*

In [ ]:
from sentence_transformers import SentenceTransformer, util
import numpy as np

In [ ]:
model = SentenceTransformer('sentence-transformers/paraphrase-multilingual-MiniLM-L12-v2')

vectors = model.encode(texts, convert_to_numpy=True)
cos_sim_matrix = util.cos_sim(vectors, vectors).numpy()


In [ ]:
print(cos_sim_matrix)

[[ 1.          0.78907603  0.14430457 -0.02929024]
 [ 0.78907603  1.          0.13725184 -0.06058992]
 [ 0.14430457  0.13725184  0.99999976  0.11993995]
 [-0.02929024 -0.06058992  0.11993995  0.9999999 ]]
